#!/usr/bin/env python3
"""
remap_fund_metrics_to_regular.py

One-time remap of fund_metrics.parquet (the IEC-1 regression factor model:
beta_drift, alpha_ann, r_squared, n_months) from direct-plan scheme codes to
the corresponding regular-plan codes, using mf_data/direct_to_regular_map.csv.

Unlike holdings (identical across plans), the factor model is computed from NAV
returns, which differ between regular and direct plans by the TER gap. So the
remapped alpha_ann carries a small bias (~0.5-1%/yr); factor sensitivities
(beta_drift, r_squared) are largely plan-independent. This is a pragmatic
restore — the rigorous alternative is recomputing the regression on regular
NAVs. fund_metrics is a static input (not regenerated by the monthly pipeline),
so this only needs to run once after the direct->regular universe switch.

Usage:
    python3 remap_fund_metrics_to_regular.py --dry-run
    python3 remap_fund_metrics_to_regular.py
"""
from __future__ import annotations

import argparse
import logging
import shutil
from pathlib import Path

import pandas as pd

logging.basicConfig(level=logging.INFO,
                    format="%(asctime)s  %(levelname)-8s  %(message)s",
                    datefmt="%H:%M:%S")
log = logging.getLogger("alphapicker.remap_fm")

HERE = Path(__file__).parent


def main() -> None:
    p = argparse.ArgumentParser(description="Remap fund_metrics scheme codes: direct -> regular")
    p.add_argument("--data-dir", default=None, help="Path to mf_data directory")
    p.add_argument("--mf-data",  default=str(HERE / "mf_data"), help="Alias for --data-dir")
    p.add_argument("--dry-run",  action="store_true", help="Report only — do not write")
    args = p.parse_args()

    mf_data    = Path(args.data_dir or args.mf_data)
    fm_path    = mf_data / "fund_metrics.parquet"
    map_path   = mf_data / "direct_to_regular_map.csv"
    meta_path  = mf_data / "fund_meta.parquet"

    for fp in (fm_path, map_path, meta_path):
        if not fp.exists():
            log.error(f"Missing file: {fp}")
            return

    fm   = pd.read_parquet(fm_path)
    mp   = pd.read_csv(map_path)
    reg  = set(pd.read_parquet(meta_path)["scheme_code"].astype(int))
    code_map = dict(zip(mp["direct_code"].astype(int), mp["regular_code"].astype(int)))

    fm["scheme_code"] = fm["scheme_code"].astype(int)

    # ── Idempotency guard: bail if already regular-coded ─────────────────
    overlap = fm["scheme_code"].isin(reg).mean()
    if overlap >= 0.5:
        log.warning(f"fund_metrics already looks regular-coded "
                    f"({overlap:.0%} in regular meta). Skipping.")
        return

    before = len(fm)
    fm["scheme_code"] = fm["scheme_code"].map(lambda c: code_map.get(int(c)))
    fm = fm[fm["scheme_code"].notna()].copy()
    fm["scheme_code"] = fm["scheme_code"].astype(int)
    fm = fm[fm["scheme_code"].isin(reg)]
    # A direct code maps to exactly one regular code, but guard against dups
    fm = fm.drop_duplicates(subset="scheme_code", keep="first")
    after = len(fm)

    log.info(f"fund_metrics: {before} direct rows -> {after} regular rows")
    if args.dry_run:
        log.info("Dry run — file NOT written.")
        return

    shutil.copy(fm_path, mf_data / "fund_metrics_direct_backup.parquet")
    fm.to_parquet(fm_path, index=False)
    log.info(f"✓ Written {after} rows (backup -> fund_metrics_direct_backup.parquet)")
    log.info("Next: re-run compute_scored_funds.py + generate_api_json.py")


if __name__ == "__main__":
    main()
